apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ushaflow-web
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: ushaflow-web
          servicePort: http